name: Build APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: uses: ArtemSerebrennikov/buildozer-action@v1


      - name: Build with Buildozer
        uses: kivy/buildozer-action@master
        with:
          buildozer_version: stable
          command: buildozer android debug
